# OutputTestPETModule.mac
/vis/disable
#/control/execute vis.mac

## Scintillator Geometry
## Pixel size: 3.2 mm
## Pixel Array: 16 x 16
## Pixel Pitch: 3.2 x 3.2 mm
## Detector surface size: 50x50 mm^2
## Detector thickness:
## Layer 0 BGO: 10 mm
## Layer 1 CZC: 25 mm

#/vis/open OGLIX
#/vis/viewer/set/viewpointThetaPhi -30 30
#/vis/viewer/set/viewpointThetaPhi 30 -20
#/vis/viewer/zoom 3.0
#/vis/drawVolume
#/tracking/storeTrajectory 1
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate 100
#/vis/scene/add/axes

/gate/geometry/setMaterialDatabase GateMaterials.db

# Geometry

# W O R L D
/gate/world/geometry/setXLength 10 cm
/gate/world/geometry/setYLength 10 cm
/gate/world/geometry/setZLength 10 cm
/gate/world/vis/setVisible 0

#################################Detector#################################

# C Y L I N D R I C A L
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/systemType cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/geometry/setRmax 10 cm
/gate/cylindricalPET/geometry/setRmin 0 cm
/gate/cylindricalPET/geometry/setHeight 10 cm
/gate/cylindricalPET/vis/forceWireframe
/gate/world/vis/setVisible 0

# R S E C T O R
/gate/cylindricalPET/daughters/name PETHead
/gate/cylindricalPET/daughters/insert box
/gate/PETHead/placement/setTranslation  0. 0. 0. mm
/gate/PETHead/geometry/setXLength 56.000000 mm
/gate/PETHead/geometry/setYLength 41.000000 mm
/gate/PETHead/geometry/setZLength 56.000000 mm
/gate/PETHead/placement/setRotationAxis 0 0 1
/gate/PETHead/placement/setRotationAngle 0. deg
/gate/PETHead/placement/setTranslation  0. 0. 0. mm
/gate/PETHead/setMaterial Air
/gate/PETHead/vis/forceWireframe
/gate/PETHead/vis/setVisible 0

# M O D U L E
/gate/PETHead/daughters/name PETModule
/gate/PETHead/daughters/insert box
/gate/PETModule/geometry/setXLength 53.000000 mm
/gate/PETModule/geometry/setYLength 38.000000 mm
/gate/PETModule/geometry/setZLength 53.000000 mm
/gate/PETModule/placement/setRotationAxis 1 0 0
/gate/PETModule/placement/setRotationAngle 0. deg
/gate/PETModule/setMaterial Air
/gate/PETModule/vis/forceWireframe
/gate/PETModule/vis/setVisible 0

# S U B M O D U L E
# Scanner Head
/gate/PETModule/daughters/name PETSubModule
/gate/PETModule/daughters/insert box
/gate/PETSubModule/geometry/setXLength 52.000000 mm
/gate/PETSubModule/geometry/setYLength 37.000000 mm
/gate/PETSubModule/geometry/setZLength 52.000000 mm
/gate/PETSubModule/setMaterial Air
/gate/PETSubModule/vis/forceWireframe
/gate/PETSubModule/vis/setVisible 0

#
# C R Y S T A L
# Pixel
/gate/PETSubModule/daughters/name PETCrystal
/gate/PETSubModule/daughters/insert box
/gate/PETCrystal/geometry/setXLength 3.200000 mm
/gate/PETCrystal/geometry/setYLength 35. mm
/gate/PETCrystal/geometry/setZLength 3.200000 mm
/gate/PETCrystal/placement/setTranslation  0. 0. 0. mm
/gate/PETCrystal/setMaterial Air
/gate/PETCrystal/vis/setColor magenta
/gate/PETCrystal/vis/setVisible 0
/gate/PETCrystal/repeaters/insert cubicArray

## L A Y E R 0
/gate/PETCrystal/daughters/name CZC
/gate/PETCrystal/daughters/insert box
/gate/CZC/geometry/setXLength 3.200000 mm
/gate/CZC/geometry/setYLength 25. mm
/gate/CZC/geometry/setZLength 3.200000 mm
/gate/CZC/placement/setTranslation 0 -5.0 0 mm
/gate/CZC/setMaterial CZC
/gate/CZC/vis/setColor yellow

##  L A Y E R 1
/gate/PETCrystal/daughters/name BGO
/gate/PETCrystal/daughters/insert box
/gate/BGO/geometry/setXLength 3.200000 mm
/gate/BGO/geometry/setYLength 10. mm
/gate/BGO/geometry/setZLength 3.200000 mm
/gate/BGO/placement/setTranslation 0 12.5 0 mm
/gate/BGO/setMaterial BGO
/gate/BGO/vis/setColor blue

# R E P E A T C R Y S T A L
/gate/PETCrystal/cubicArray/setRepeatNumberX 16
/gate/PETCrystal/cubicArray/setRepeatNumberY 1
/gate/PETCrystal/cubicArray/setRepeatNumberZ 16
/gate/PETCrystal/cubicArray/setRepeatVector 3.2 0. 3.2 mm

#
##	A T T A C H    S Y S T E M 
/gate/systems/cylindricalPET/rsector/attach   PETHead
/gate/systems/cylindricalPET/module/attach    PETModule
/gate/systems/cylindricalPET/crystal/attach   PETCrystal
/gate/systems/cylindricalPET/layer0/attach    CZC
/gate/systems/cylindricalPET/layer1/attach    BGO

#	A T T A C H    C R Y S T A L  SD

/gate/CZC/attachCrystalSD
/gate/BGO/attachCrystalSD

/gate/systems/cylindricalPET/describe


# Phantom/Source
/gate/cylindricalPET/daughters/name Phantom
/gate/cylindricalPET/daughters/insert box
/gate/Phantom/geometry/setXLength 0.00001 mm
/gate/Phantom/geometry/setYLength 0.00001 mm
/gate/Phantom/geometry/setZLength 0.00001 mm
#/gate/Phantom/geometry/setXLength 10. mm
#/gate/Phantom/geometry/setYLength 10. mm
#/gate/Phantom/geometry/setZLength 10. mm
/gate/Phantom/placement/setTranslation  0. -30. 0. mm
/gate/Phantom/setMaterial Air
/gate/Phantom/vis/setColor red
/gate/Phantom/vis/forceWireframe
/gate/Phantom/vis/setVisible 1
/gate/Phantom/attachPhantomSD

# Physics
/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel e-
/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel PenelopeModel
/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel
/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/addProcess eMultipleScattering e-

/gate/physics/processList Enabled
/gate/physics/processList Initialized

# Cuts
/gate/physics/Gamma/SetCutInRegion PETHead 1 cm
/gate/physics/Electron/SetCutInRegion PETHead 1 cm
/gate/physics/Electron/SetCutInRegion PETHead 1 cm
/gate/physics/Gamma/SetCutInRegion Phantom 0.1 cm
/gate/physics/Electron/SetCutInRegion Phantom 0.1 cm
/gate/physics/SetMaxStepSizeInRegion Phantom 0.1 cm
/gate/physics/displayCuts

# Initialization (1)
/gate/run/initialize

# Source
/gate/source/addSource S49
/gate/source/S49/gps/pos/type Volume
/gate/source/S49/gps/pos/shape Cylinder
/gate/source/S49/gps/pos/centre 0. 0. 0. cm
/gate/source/S49/gps/pos/radius 0.0100000 cm
/gate/source/S49/gps/pos/halfz 0.01 cm
/gate/source/S49/gps/particle gamma
/gate/source/S49/gps/energy 511. keV
#/gate/source/S49/setActivity 1000000 Bq # 1 MBq
/gate/source/S49/setActivity 100000 Bq # 100 kBq
/gate/source/S49/gps/angtype iso
/gate/source/S49/gps/mintheta 90. deg
/gate/source/S49/gps/maxtheta 90. deg
/gate/source/S49/gps/minphi -90. deg
/gate/source/S49/gps/maxphi -90. deg
/gate/source/S49/setForcedHalfLife 6586.2 s # assuming F18

/gate/source/list
/gate/source/S49/attachTo Phantom

# Digitizer
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.1
/gate/digitizer/Singles/blurring/setEnergyOfReference 140. keV
/gate/digitizer/Singles/insert spblurring
/gate/digitizer/Singles/spblurring/setSpresolution 2.0 mm
/gate/digitizer/Singles/spblurring/verbose 0
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 10. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 154. keV


# Output
#/gate/output/root/enable
/gate/output/root/disable
#/gate/output/root/setFileName ./Outputs/TestPhoswich
#/gate/output/root/setRootHitsFlag 0
#/gate/output/root/setRootSinglesFlag 1
#/gate/output/root/setRootSinglesAdderFlag 0
#/gate/output/root/setRootSinglesBlurringFlag 0
#/gate/output/root/setRootSinglesSpblurringFlag 0
#/gate/output/root/setRootSinglesThresholderFlag 0
#/gate/output/root/setRootSinglesUpholderFlag 0

#/gate/output/binary/enable
/gate/output/binary/disable
#/gate/output/binary/setFileName ./Outputs/TestPhoswich
#/gate/output/binary/setOutFileHitsFlag 1
#/gate/output/binary/setOutFileSinglesFlag 1

/gate/output/ascii/enable
/gate/output/ascii/setFileName ./Outputs/TestPhoswich
/gate/output/ascii/setOutFileHitsFlag 1
/gate/output/ascii/setOutFileSinglesFlag 1

# Random
# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName Ranlux64
#/gate/random/setEngineSeed default
#/gate/random/setEngineSeed auto
/gate/random/setEngineSeed 123456789
#/gate/random/resetEngineFrom fileName
/gate/random/verbose 0

# Initialization (2)
/gate/run/initialize

## Experiment Time
/gate/application/setTimeSlice 0.1 s
/gate/application/setTimeStart 0 s
/gate/application/setTimeStop 0.1 s

# Verbosity
/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# L E T S   R U N   T H E   S I M U L A T I O N
/gate/application/startDAQ
